language: node_js
node_js:
  - "8"
sudo: required
services:
  - docker
before_script:
  - npm -g install @oracle/ojet-cli
script:
  - docker build -t spikehip/airos-4-rest:$TRAVIS_BUILD_NUMBER api
  - cd web-client
  - npm install
  - ojet build web --release
  - sed -i "s/__BUILD_VERSION__/$TRAVIS_COMMIT/" web/index.html
  - cd ..
  - docker build -t spikehip/airos-4-client:$TRAVIS_BUILD_NUMBER web-client
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push spikehip/airos-4-rest;
    docker push spikehip/airos-4-client;
    fi
before_deploy:
  - tar -cvzf web-client-stable.tar.gz -C web-client/web/ .
deploy:
  provider: releases
  user: "spikehip"
  password: $GITHUB_PASSWORD
  file: "web-client-stable.tar.gz" 
  skip_cleanup: true
  on:
    tags: true
