language: node_js
node_js:
  - "8"
sudo: required
services:
  - docker
before_script:
  - npm -g install @oracle/ojet-cli
script:
  - docker build -t spikehip/airos-4-rest api
  - cd web-client
  - npm install
  - ojet build web --release
  - cd ..
  - docker build -t spikehip/airos-4-client web-client
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push spikehip/airos-4-rest;
    docker push spikehip/airos-4-client;
    docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $SWARM
    export DOCKER_HOST=tcp://127.0.0.1:32768
    docker run -p 80:80 -d spikehip/airos-4-client
    fi
